# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
#
language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      after_success:
        - pyinstaller --onefile skilletcli.py
        - ls -l dist
      deploy:
        - provider: pypi
          user: "abigserve"
          password: $pypi_pw
          on:
            tags: true

        - provider: releases
          api_key: $api_token
          file:
            - "dist/skilletcli"
          skip_cleanup: true
          on:
            tags: true

    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers ; pip3 install pytest
      after_success:
        - pyinstaller --onefile skilletcli.py --windowed
        - mv dist/skilletcli dist/skilletcli-mac
        - ls -l dist
      deploy:
        provider: releases
        api_key: $api_token
        file:
          - "dist/skilletcli-mac"
        skip_cleanup: true
        on:
          tags: true

    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install:
        - choco install python --version=3.7.2  # this install takes at least 1 min 30 sec
        - python -m pip install --upgrade pip
        - python -m pip install pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      after_success:
        - pyinstaller --onefile skilletcli.py
        - dir dist
      deploy:
        - provider: releases
          api_key: $api_token
          file:
            - "dist/skilletcli.exe"
          skip_cleanup: true
          on:
            tags: true

script: pytest
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install pyinstaller
notifications:
  email: false