# variables list to set values used in tools for local configs
variables:
  - name: PANORAMA_NAME
    description: Panorama hostname
    value: panorama01
# Panorama mgmt inteface type and if static update the IP info
# DHCP is used for cloud deployments only
  - name: PANORAMA_TYPE
    description: Panorama management IP type - static or cloud (for dhcp)
    value: cloud
  - name: PANORAMA_IP
    description: Panorama IP
    value: 192.168.55.8
  - name: PANORAMA_MASK
    description: Panorama netmask
    value: 255.255.255.0
  - name: PANORAMA_DG
    description: Panorama default gateway
    value: 192.168.55.2
  - name: CONFIG_EXPORT_IP
    description: IP address for scheduled config exports
    value: 192.0.2.3
  - name: TEMPLATE
    description: Template name for Panorama
    value: iron-skillet
  - name: STACK
    description: Template stack name for Panorama
    value: iron-skillet-stack
  - name: DEVICE_GROUP
    description: Device-group name for Panorama
    value: iron-skillet
  - name: FW_NAME
    description: Device Name for NGFW
    value: sample
# Management interface type of dhcp or static
# If static be sure to set the IP attributes
  - name: MGMT_TYPE
    description: firewall management IP type (static or dhcp-client)
    value: dhcp-client
  - name: MGMT_IP
    description: NGFW management IP
    value: 192.0.2.6
  - name: MGMT_MASK
    description: NGFW management netmask
    value: 255.255.128.0
  - name: MGMT_DG
    description: NGFW management default gateway
    value: 192.0.2.7
  - name: NTP_1
    description: Network Time Protocol Server
    value: 0.pool.ntp.org
  - name: NTP_2
    description: Network Time Protocol Server 2
    value: 1.pool.ntp.org
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    value: admin
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    value: admin
  - name: DNS_1
    description: primary dns server
    value: 8.8.8.8
  - name: DNS_2
    description: secondary dns server
    value: 8.8.4.4
  - name: SINKHOLE_IPV4
    description: sinkhole address IPv4
    value: 72.5.65.111
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    value: 2600:5200::1
  - name: INTERNET_ZONE
    description: untrust zone to filter out in reports
    value: internet
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    value: 192.0.2.1
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    value: sentfrom@yourdomain.com
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    value: sendto@yourdomain.com
  - name: SYSLOG_SERVER
    description: syslog server ip address
    value: 192.0.2.2
  - name: INCLUDE_PAN_EDL
    description: include the predefined Palo Alto Networks external lists
    value: 'yes'

  - name: API_KEY_LIFETIME
    value: 525600

  - name: GP_ID
    value: gp_userid

  - name: LDAP_SERVER
    value: 192.168.1.141

  - name: LDAP_BINDDN
    value: userid@esxlab.com

  - name: LDAP_BINDPASSWORD
    value: spaghett

  - name: LDAP_BASEDN
    value: DC=esxlab,DC=com

  - name: ALLOWED_GROUPS
    value:
      - esxlab\administrators

  - name: GP_PORTAL_IP
    value: 10.10.10.250

  - name: GP_PORTAL_INT
    value: loopback.99

  - name: GP_EXTERNAL_GW_ADDR
    value: 10.10.10.251

  - name: GP_EXTERNAL_GW_INTERFACE
    value: loopback.100

  - name: IP_POOL
    value: 10.10.200.0/24

  - name: CLIENT_PRIMARY_DNS
    value: 8.8.8.8

  - name: CLIENT_SECONDARY_DNS
    value: 8.8.4.4

  - name: CLIENT_DNS_SUFFIX
    value:
      - esxlab.com

  - name: TUNNEL_INTERFACE
    value: tunnel.50

  - name: TUNNEL_ZONE
    value: INSIDE

  - name: VR
    value: default

  - name: GP_EXTERNAL_GW_DNS
    value: egw-test.org.com

  - name: PORTAL_SSL_PROFILE
    value: portal

  - name: EGW_SSL_PROFILE
    value: egw

  - name: sdwan_branch_template
    value: test

  - name: sdwan_hub_template
    value: test_hub

  - name: sdwan_branch_stack
    value: test_stack

  - name: sdwan_hub_stack
    value: test_hub_stack